const products=[
{id:1,name:'Frank Cyclone — Black',cat:'Jockstrap',price:29.90,img:'https://maskulo.nl/cdn/shop/files/mjs199-y1-frank-cyclone-jockstrap-with-removable-pouch-black-480772.webp?v=1754462604',sizes:['S-M','L-XL']},
{id:2,name:'Gary Cyclone — Army Green',cat:'Jockstrap',price:34.90,img:'https://maskulo.com/cdn/shop/files/mjs200-y1-gary-cyclone-jockstrap-with-removable-pouch-army-green-315030.webp?v=1754462601',sizes:['S-M','L-XL']},
{id:3,name:'Kyle Steelguard Mesh — Camo/White',cat:'Jockstrap',price:29.90,img:'https://maskulo.de/cdn/shop/files/mjs186-y2-kyle-steelguard-mesh-jockstrap-camouflage-white-617190.webp?v=1754462607&width=1500',sizes:['S','M','L','XL','XXL']},
{id:4,name:'Captain-A Brief — Royal Blue',cat:'Brief',price:34.90,img:'https://maskulo.de/cdn/shop/files/mbr141-y2-captain-a-briefs-with-o-inside-pouch-blue-royal-and-white-459666.webp?v=1754462807&width=1500',sizes:['S','M','L','XL']},
{id:5,name:'Ken Gridd-Iron — Black/White',cat:'Jockstrap',price:29.90,img:'https://maskulo.us/cdn/shop/files/mjs187-y1-ken-gridd-iron-american-football-jockstrap-black-white-926071.webp?v=1753175231&width=1200',sizes:['S-M','L-XL']},
{id:6,name:'Dash Cyclone — Red',cat:'Jockstrap',price:39.90,img:'https://maskulo.com/cdn/shop/files/mjs190-y1-dash-cyclone-jockstrap-with-removable-pouch-red-530504.webp?v=1754462606',sizes:['S-M','L-XL']},
{id:7,name:'Cork Cyclone — Royal Blue',cat:'Jockstrap',price:34.90,img:'https://maskulo.us/cdn/shop/files/mjs201-y1-cork-cyclone-jockstrap-with-removable-pouch-royal-blue-185602.webp?v=1753175316',sizes:['S-M','L-XL']},
{id:8,name:'Eugene Cyclone — White',cat:'Jockstrap',price:49.90,img:'https://maskulo.uk/cdn/shop/files/mjs189-y1-eugene-cyclone-jockstrap-with-removable-pouch-white-551286.webp?v=1764255579&width=1500',sizes:['S-M','L-XL']},
{id:9,name:'Maskulo Armored — Black',cat:'Brief',price:59.90,img:'https://maskulo.uk/cdn/shop/collections/mens-briefs-465285.png?v=1741557347',sizes:['S','M','L','XL']},
{id:10,name:'Armored Collection Look',cat:'Clubwear',price:69.90,img:'https://maskulo.uk/cdn/shop/collections/armored-collection-983253.png?v=1741557184',sizes:['S','M','L','XL']},
{id:11,name:'MY.SIZE PRO — 3 Preservativos',cat:'Proteção',price:5.90,img:'https://pro.mysize-condoms.com/fileadmin/user_upload/MYSIZE_Pack-3er-72_768x711px.png',sizes:['45','47','49','53','57','60','64','69','72']}
];
const dict={pt:{add:'ADICIONAR',added:'ADICIONADO ✓',qty:'Qtd.',remove:'Remover',empty:'Seu carrinho está vazio.',error:'Não foi possível abrir o pagamento. Tente novamente.',option:'Opção'},fr:{add:'AJOUTER',added:'AJOUTÉ ✓',qty:'Qté',remove:'Retirer',empty:'Votre panier est vide.',error:'Impossible d’ouvrir le paiement. Réessayez.',option:'Option'},en:{add:'ADD TO CART',added:'ADDED ✓',qty:'Qty',remove:'Remove',empty:'Your cart is empty.',error:'Could not open payment. Please try again.',option:'Option'},es:{add:'AÑADIR',added:'AÑADIDO ✓',qty:'Cant.',remove:'Eliminar',empty:'Tu carrito está vacío.',error:'No se pudo abrir el pago. Inténtalo de nuevo.',option:'Opción'}};
let lang=(navigator.language||'pt').slice(0,2);if(!dict[lang])lang='en';const t=dict[lang];
const euro=n=>new Intl.NumberFormat(lang==='pt'?'pt-PT':lang==='fr'?'fr-BE':lang==='es'?'es-ES':'en-IE',{style:'currency',currency:'EUR'}).format(n);
let cart=[];try{cart=JSON.parse(localStorage.getItem('ldrCart')||'[]')}catch(e){cart=[]}
function save(){localStorage.setItem('ldrCart',JSON.stringify(cart));updateCart()}
function render(){grid.innerHTML=products.map(p=>`<article class="card"><div class="pic"><img src="${p.img}" alt="${p.name}" loading="lazy"></div><div class="cardBody"><h3>${p.name}</h3><strong class="price">${euro(p.price)}</strong><select class="optionSelect" id="opt-${p.id}" aria-label="${t.option}">${p.sizes.map(s=>`<option value="${s}">${s}</option>`).join('')}</select><div class="buyRow"><label>${t.qty}<input class="qtyInput" id="qty-${p.id}" type="number" min="1" max="20" value="1"></label><button class="add" type="button" onclick="addToCart(${p.id},this)">${t.add}</button></div></div></article>`).join('')}
function addToCart(id,btn){const p=products.find(x=>x.id===id),option=document.getElementById(`opt-${id}`).value,qty=Math.max(1,Math.min(20,parseInt(document.getElementById(`qty-${id}`).value)||1));const key=`${id}-${option}`,found=cart.find(x=>x.key===key);if(found)found.qty=Math.min(20,found.qty+qty);else cart.push({key,id,name:p.name,price:p.price,option,qty});save();btn.textContent=t.added;setTimeout(()=>btn.textContent=t.add,900);openCart()}
function changeQty(key,delta){const x=cart.find(i=>i.key===key);if(!x)return;x.qty=Math.max(1,Math.min(20,x.qty+delta));save()}
function removeItem(key){cart=cart.filter(x=>x.key!==key);save()}
function updateCart(){const count=cart.reduce((s,x)=>s+x.qty,0),total=cart.reduce((s,x)=>s+x.price*x.qty,0);cartCount.textContent=count;cartTotal.textContent=euro(total);cartItems.innerHTML=cart.length?cart.map(x=>`<div class="cartItem"><div><strong>${x.name}</strong><small>${t.option}: ${x.option}</small><span>${euro(x.price)}</span></div><div class="qtyControl"><button onclick="changeQty('${x.key}',-1)">−</button><b>${x.qty}</b><button onclick="changeQty('${x.key}',1)">+</button><button class="remove" onclick="removeItem('${x.key}')">${t.remove}</button></div></div>`).join(''):`<p>${t.empty}</p>`;checkoutButton.disabled=!cart.length}
function openCart(){cartDrawer.classList.add('open');shade.classList.add('open')}
function closeCart(){cartDrawer.classList.remove('open');shade.classList.remove('open')}
cartButton.onclick=openCart;closeCart.onclick=closeCart;continueButton.onclick=closeCart;shade.onclick=closeCart;
checkoutButton.onclick=async()=>{if(!cart.length)return;checkoutButton.disabled=true;cartMessage.textContent='...';try{const r=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:cart.map(({id,option,qty})=>({id,option,qty}))})});const d=await r.json();if(!r.ok||!d.url)throw new Error(d.error||'checkout');location.href=d.url}catch(e){cartMessage.textContent=t.error;checkoutButton.disabled=false}}
if(new URLSearchParams(location.search).get('payment')==='success'){cart=[];save()}
render();updateCart();